AG_beta6/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataLayer6;

namespace AG_beta6.Controllers
{
    [Authorize]
    public class ClienteController : Controller
    {
        private DBControlTaxi db = new DBControlTaxi();

        // GET: Cliente
        public async Task<ActionResult> Index(string message)
        {
            ViewBag.Message = message;
            var cliente = db.Cliente.Include(c => c.Empresa);
            return View(await cliente.ToListAsync());
        }

        // GET: Cliente/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {
            ViewBag.IdEmpresa = new SelectList(db.Empresa, "Id_empr", "Nombre");
            return View();
        }

        // POST: Cliente/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Rut,Dig,Nombre,Apellidos,Telefono,IdEmpresa,Id_Clie")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                cliente.Rut = cliente.Rut.Replace(".", "");
                db.Cliente.Add(cliente);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { message = "success" });
            }

            ViewBag.IdEmpresa = new SelectList(db.Empresa, "Id_empr", "Rut", cliente.IdEmpresa);
            return View(cliente);
        }

        // GET: Cliente/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdEmpresa = new SelectList(db.Empresa, "Id_empr", "Rut", cliente.IdEmpresa);
            return View(cliente);
        }

        // POST: Cliente/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Rut,Dig,Nombre,Apellidos,Telefono,IdEmpresa,Id_Clie")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                cliente.Rut = cliente.Rut.Replace(".", "");
                db.Entry(cliente).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { message = "success" });
            }
            ViewBag.IdEmpresa = new SelectList(db.Empresa, "Id_empr", "Rut", cliente.IdEmpresa);
            return View(cliente);
        }

        // GET: Cliente/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Cliente cliente = await db.Cliente.FindAsync(id);
            db.Cliente.Remove(cliente);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AG_beta6/Controllers/PerfilController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataLayer6;

namespace AG_beta6.Controllers
{
    [Authorize]
    public class PerfilController : Controller
    {
        private DBControlTaxi db = new DBControlTaxi();

        // GET: Perfil
        public async Task<ActionResult> Index(string message)
        {
            ViewBag.Message = message;
            return View(await db.Perfil.ToListAsync());
        }

        // GET: Perfil/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Perfil perfil = await db.Perfil.FindAsync(id);
            if (perfil == null)
            {
                return HttpNotFound();
            }
            return View(perfil);
        }

        // GET: Perfil/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Perfil/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id_Perfil,Dsc_Perfil")] Perfil perfil)
        {
            if (ModelState.IsValid)
            {
                db.Perfil.Add(perfil);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { message = "success" });
            }

            return View(perfil);
        }

        // GET: Perfil/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Perfil perfil = await db.Perfil.FindAsync(id);
            if (perfil == null)
            {
                return HttpNotFound();
            }
            return View(perfil);
        }

        // POST: Perfil/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id_Perfil,Dsc_Perfil")] Perfil perfil)
        {
            if (ModelState.IsValid)
            {
                db.Entry(perfil).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { message = "success" });
            }
            return View(perfil);
        }

        // GET: Perfil/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Perfil perfil = await db.Perfil.FindAsync(id);
            if (perfil == null)
            {
                return HttpNotFound();
            }
            return View(perfil);
        }

        // POST: Perfil/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Perfil perfil = await db.Perfil.FindAsync(id);
            db.Perfil.Remove(perfil);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AG_beta6/Controllers/ViajesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataLayer6;

namespace AG_beta6.Controllers
{
    [Authorize]
    public class ViajesController : Controller
    {
        private DBControlTaxi db = new DBControlTaxi();

        // GET: Viajes
        public async Task<ActionResult> Index(string message)
        {
            ViewBag.Message = message;
            var viaje = db.Viaje.Include(v => v.Cliente).Include(v => v.Conductor).Include(v => v.estado);
            return View(await viaje.ToListAsync());
        }

        // GET: Viajes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Viaje viaje = await db.Viaje.FindAsync(id);
            if (viaje == null)
            {
                return HttpNotFound();
            }
            return View(viaje);
        }

        // POST: Json Valor Empresa
        [HttpPost]
        public ActionResult GetValorTarifa(int? IdPasajero)
        {
            if (IdPasajero != null)
            {
                int valor_bndra = db.Cliente.Find(IdPasajero).Empresa.Tarifa.Valor_bndra;
                int valor_mtr = db.Cliente.Find(IdPasajero).Empresa.Tarifa.Valor_mts;
                int[] valores = new int[] { valor_bndra, valor_mtr };
                return Json(valores);
            }
            else
            {
                return Json("An Error Has occoured");
            }
        }

        // GET: Viajes/Create
        public ActionResult Create()
        {
            ViewBag.IdPasajero = new SelectList(db.Cliente, "Id_Clie", "Nombre", "Seleccione un pasajero");
            ViewBag.RutConductor = new SelectList(db.Conductor, "Rut", "Nombre", "Seleccione un conductor");
            ViewBag.IdEstado = new SelectList(db.estado, "Id_Estado", "Nombre", "Seleccione un estado");
            return View();
        }

        // POST: Viajes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id_viaje,Origen,Destino,Km,Valor,Valor_bndra,Valor_mts,FechaInicio,HoraIni,FechaTermino,HoraTer,IdPasajero,RutConductor,IdEstado,Latitud_des,Longitud_des,Latitud_ori,Longitud_ori")] Viaje viaje)
        {
            if (ModelState.IsValid)
            {
                db.Viaje.Add(viaje);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { message = "success" });
            }

            ViewBag.IdPasajero = new SelectList(db.Cliente, "Id_Clie", "Rut", viaje.IdPasajero);
            ViewBag.RutConductor = new SelectList(db.Conductor, "Rut", "Dig", viaje.RutConductor);
            ViewBag.IdEstado = new SelectList(db.estado, "Id_Estado", "Nombre", viaje.IdEstado);
            return View(viaje);
        }

        // GET: Viajes/Reporte
        public async Task<ActionResult> ReporteViajes(DateTime? start, DateTime? end)
        {
            string stringdatestart = "";
            string stringdatesend = "";
            var viaje = db.Viaje.Include(v => v.Cliente).Include(v => v.Conductor).Include(v => v.estado);
            if (start != null && end != null) 
            {
                viaje = db.Viaje.Where(x => x.FechaInicio >= start && x.FechaInicio <= end).Include(v => v.Cliente).Include(v => v.Conductor).Include(v => v.estado);
                stringdatestart = start.Value.ToString("yyyy/MM/dd");
                stringdatesend = end.Value.ToString("yyyy/MM/dd");
            }
            ViewBag.start = stringdatestart;
            ViewBag.end = stringdatesend;
            return View(await viaje.ToListAsync());
        }

        // GET: Viajes/Reporte
        public async Task<ActionResult> CobroEmpresa(DateTime? start, DateTime? end)
        {
            string stringdatestart = "";
            string stringdatesend = "";
            var viaje = db.Viaje.Include(v => v.Cliente).Include(v => v.Conductor).Include(v => v.estado);
            if (start != null && end != null)
            {
                viaje = db.Viaje.Where(x => x.FechaInicio >= start && x.FechaInicio <= end).Include(v => v.Cliente).Include(v => v.Conductor).Include(v => v.estado);
                stringdatestart = start.Value.ToString("yyyy/MM/dd");
                stringdatesend = end.Value.ToString("yyyy/MM/dd");
            }
            ViewBag.start = stringdatestart;
            ViewBag.end = stringdatesend;
            return View(await viaje.ToListAsync());
        }

        // GET: Viajes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Viaje viaje = await db.Viaje.FindAsync(id);
            if (viaje == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdPasajero = new SelectList(db.Cliente, "Id_Clie", "Nombre", viaje.IdPasajero);
            ViewBag.RutConductor = new SelectList(db.Conductor, "Rut", "Nombre", viaje.RutConductor);
            ViewBag.IdEstado = new SelectList(db.estado, "Id_Estado", "Nombre", viaje.IdEstado);
            return View(viaje);
        }

        // POST: Viajes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id_viaje,Origen,Destino,Km,Valor,Valor_bndra,Valor_mts,FechaInicio,HoraIni,FechaTermino,HoraTer,IdPasajero,RutConductor,IdEstado,Latitud_des,Longitud_des,Latitud_ori,Longitud_ori")] Viaje viaje)
        {
            if (ModelState.IsValid)
            {
                db.Entry(viaje).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { message = "success" });
            }
            ViewBag.IdPasajero = new SelectList(db.Cliente, "Id_Clie", "Nombre", viaje.IdPasajero);
            ViewBag.RutConductor = new SelectList(db.Conductor, "Rut", "Nombre", viaje.RutConductor);
            ViewBag.IdEstado = new SelectList(db.estado, "Id_Estado", "Nombre", viaje.IdEstado);
            return View(viaje);
        }

        // GET: Viajes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Viaje viaje = await db.Viaje.FindAsync(id);
            if (viaje == null)
            {
                return HttpNotFound();
            }
            return View(viaje);
        }

        // POST: Viajes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Viaje viaje = await db.Viaje.FindAsync(id);
            db.Viaje.Remove(viaje);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AG_beta6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Administración AG</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar glyphicon glyphicon-menu-hamburger"></span>
                </button>
                @Html.ActionLink("GesFlota", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" class="" id="menu-toggle">
                            Menú <<
                        </a>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li>
                    @Html.ActionLink("Inicio", "Index", "Home")
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Administrador"))
                    {
                        <li>
                            @Html.ActionLink("Dashboard", "Dashboard", "Home")
                        </li>
                        <li>
                            @Html.ActionLink("Reporte Conductores", "ReporteViajes", "Viajes")
                        </li>
                        <li>
                            @Html.ActionLink("Reporte Empresas", "CobroEmpresa", "Viajes")
                        </li>
                        <li>
                            @Html.ActionLink("Usuarios", "Index", "Usuario")
                        </li>
                        <li>
                            @Html.ActionLink("Perfiles", "Index", "Perfil")
                        </li>
                        <li>
                            @Html.ActionLink("Clientes", "Index", "Cliente")
                        </li>
                        <li>
                            @Html.ActionLink("Empresas", "Index", "Empresa")
                        </li>
                        <li>
                            @Html.ActionLink("Tarifas", "Index", "Tarifas")
                        </li>
                        <li>
                            @Html.ActionLink("Chofer", "Index", "Conductor")
                        </li>
                        <li>
                            @Html.ActionLink("Vehículos", "Index", "Vehiculo")
                        </li>
                        <li>
                            @Html.ActionLink("Reservas", "Index", "Reservas")
                        </li>
                        <li>
                            @Html.ActionLink("Viajes", "Index", "Viajes")
                        </li>
                        <li>
                            @Html.ActionLink("Estados", "Index", "Estados")
                        </li>
                        <!--<li>
                            @Html.ActionLink("Conducto-Vehiculo", "Index", "Conductor_vehiculo")
                        </li>-->
                    }
                    if (User.IsInRole("Operador"))
                    {
                        
                        <li>
                            @Html.ActionLink("Clientes", "Index", "Cliente")
                        </li>
    <li>
        @Html.ActionLink("Dashboard", "Dashboard", "Home")
    </li>
                        <li>
                            @Html.ActionLink("Empresas", "Index", "Empresa")
                        </li>
                        <li>
                            @Html.ActionLink("Chofer", "Index", "Conductor")
                        </li>
                        <li>
                            @Html.ActionLink("Vehículos", "Index", "Vehiculo")
                        </li>
                        <li>
                            @Html.ActionLink("Reservas", "Index", "Reservas")
                        </li>
                        <li>
                            @Html.ActionLink("Viajes", "Index", "Viajes")
                        </li>
                        <li>
                            @Html.ActionLink("Estados", "Index", "Estados")
                        </li>
    <!--<li>
        @Html.ActionLink("Conducto-Vehiculo", "Index", "Conductor_vehiculo")
    </li>-->
                    }

                }
                <li>
                    @Html.ActionLink("Acerca de", "About", "Home")
                </li>
                <li>
                    @Html.ActionLink("Contacto", "Contact", "Home")
                </li>
               
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        <div id="page-content-wrapper">
            <div class="container-fluid body-content">
                @if (ViewBag.Message != null)
                {
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong> Datos Guardados con exito.</strong>
                    </div>
                }
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Administración AG</p>
                </footer>
            </div>
        </div>
   </div>
    <script>
        $("#menu-toggle").click(function (e) {
            if ($("#wrapper").hasClass("toggled")) {
                $("#menu-toggle").text("Menú <<")
            } else {
                $("#menu-toggle").text("Menú >>")
            }
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });

        $(function () {
            $('.datetimepicker').datetimepicker({
               format: 'YYYY-MM-DD'
            });
            $('.timepicker').datetimepicker({
                format: 'HH:mm'
            });
        });
    </script>
</body>
</html>